export const requiredFields = [
  "dateOfPayment",
  "customerName",
  "amount",
  "service",
  "status",
  "mobile1",
  "email1",
  "handleBy",
  "transactionId",
  "address",
  "category",
  "country",
];

export const nonEditableFields = [
  "transactionId",
  "dateOfPayment",
  "handlerId",
];

export const hiddenFields = [
  "communication",
  "solutions",
  "solDetails",
  "overallRating",
  "remarks",
  "qualityDesc",
  "feedStatus",
  "additionalInfo",
  "feedbackComment",
  "airBillNo",
  "productsName",
  "gems3",
  "gems4",
];

export const expectedHeaders = {
  dateOfPayment: "",
  customerName: "",
  amount: "",
  pendingAmount: "",
  refund: "",
  status: "",
  service: "",
  mobile1: "",
  mobile2: "",
  email1: "",
  email2: "",
  expert: "",
  handlerId: "",
  handleBy: "",
  mode: "",
  country: "",
  state: "",
  transactionId: "",
  sheet: "",
  remark: "",
  gems: "",
  gems1: "",
  gems2: "",
  gems3: "",
  gems4: "",
  communication: "",
  solutions: "",
  solDetails: "",
  overallRating: "",
  remarks: "",
  qualityDesc: "",
  feedStatus: "",
  additionalInfo: "",
  feedbackComment: "",
  address: "",
  airBillNo: "",
  productsName: "",
  skuNo: "",
  category: "",
};

export const headerLabels = {
  dateOfPayment: "Date of Payment",
  customerName: "Customer Name",
  amount: "Amount",
  pendingAmount: "Pending Amount",
  refund: "Refund",
  status: "Status",
  service: "Service",
  mobile1: "Mobile 1",
  mobile2: "Mobile 2",
  email1: "Email 1",
  email2: "Email 2",
  expert: "Expert",
  handlerId: "Handler ID",
  handleBy: "Handle By",
  mode: "Mode",
  country: "Country",
  state: "State",
  transactionId: "Transaction ID",
  sheet: "Sheet",
  remark: "Remark",
  gems: "Gems",
  gems1: "Gems 1",
  gems2: "Gems 2",
  gems3: "Gems 3",
  gems4: "Gems 4",
  communication: "Communication",
  solutions: "Solutions",
  solDetails: "Sol Details",
  overallRating: "Overall Rating",
  remarks: "Remarks",
  qualityDesc: "Quality Desc",
  feedStatus: "Feed Status",
  additionalInfo: "Additional Info",
  feedbackComment: "Feedback Comment",
  address: "Address",
  airBillNo: "Air Bill No.",
  productsName: "Product Name",
  skuNo: "SKU NO.",
  category: "Category",
};

export const dropdownOptions = {
  status: ["Paid", "Pending", "Refunded","Consultation Done"],
  service: [
    "Acne Treatment in Medical Astrology",
    "Acquisition Report",
    "ADHD Treatment in Medical Astrology",
    "AIDS Treatment in Medical Astrology",
    "Alcoholism Treatment by Medical Astrology",
    "Alzheimer's Treatment in Medical Astrology",
    "Anemia Treatment in Medical Astrology",
    "Arthritis Treatment in Medical Astrology",
    "Ask any corp. question",
    "Astro Consultation Single Question",
    "Astrology Consultancy",
    "Astrology Health Analysis Report",
    "Astrological Cure for Low Sex Drive | Medical Astrology Remedies for Libido",
    "Astrological Remedies for Childless Couple",
    "Autism Treatment in Medical Astrology",
    "Auto-Immune Disease",
    "Auspicious Muhurat",
    "Azoospermia Treatment in Medical Astrology",
    "Baby Name Selection",
    "Baglamukhi or Pitambara Yagya",
    "Birth Time Rectification",
    "Birth Time Selection",
    "Black Magic Removal",
    "Blood Pressure Treatment In Medical Astrology",
    "Bollywood Astrological Career Growth Report",
    "Bollywood Astrology Consultation",
    "Bollywood Numerology Report-Consultation",
    "Bollywood Tarot Card Reading",
    "Bollywood Tarot Reading - Specific Question",
    "Brain Tumor Treatment in Medical Astrology",
    "Breast Cancer Treatment in Medical Astrology",
    "Budh (Mercury) Yagya",
    "Business Family Report",
    "Business Name Numerology",
    "Business Report",
    "Cancer Treatment in Medical Astrology",
    "Cardiac Arrest Treatment in Medical Astrology",
    "Career Astrology Foreign Settlement",
    "Career Astrology Report Online",
    "Career Counselling and Guidance",
    "Career Guidance using Chakra Analysis",
    "Cataract Treatment in Medical Astrology",
    "Cerebral palsy treatment in Medical Astrology",
    "Chakra Activation for Health",
    "Chandra (Moon) Yagya",
    "Child Astrology Consultation",
    "Child Career Report One Year",
    "Child Education",
    "Chicken Gunya Treatment In Medical Astrology",
    "Chickenpox Treatment in Medical Astrology | Ayurvedic & Planetary Remedies",
    "Coma Treatment in Medical Astrology",
    "Compatibility Analysis",
    "Compatibility Analysis Report",
    "Corporate Astrology",
    "Corporate Muhurta Report",
    "Corporate vastu",
    "Court Cases Victory by Disputes Yagya",
    "Current business analysis",
    "Danger averting Yagya",
    "Dengue Treatment In Medical Astrology",
    "Depression Treatment in Medical Astrology",
    "Diabetes Treatment in Medical Astrology",
    "Diversification Analysis",
    "Dyslexia Treatment in Medical Astrology",
    "Elephantiasis Treatment in Medical Astrology",
    "Employee Scan",
    "Enlarged Prostrate Treatment in Medical Astrology",
    "Epilepsy Treatment in Medical Astrology",
    "Erectile Dysfunction Treatment in Medical Astrology",
    "Face to Face Consultation with Astrologer Prashant Kapoor (1 hour)",
    "Face to Face Consultation with Astrologer Prashant Kapoor (30 minutes)",
    "Fabry Disease Treatment In Medical Astrology",
    "Family Astrology",
    "Family Astrology 2025",
    "Family Astrology AMC",
    "Female Infertility Treatment in Medical Astrology",
    "Finance Report Astrology",
    "Financial Stability in Bollywood",
    "Fibroids Treatment in Medical Astrology",
    "Fistula Treatment in Medical Astrology",
    "Five Years Astrological Predictions",
    "Free Astrology Consultation",
    "Free Gemstone Recommendation",
    "Future Astrology & Numerology Report 5 years Prediction",
    "Future Astrology & Numerology Report of 30 Years",
    "Gallstones Removal in Medical Astrology",
    "Graphological Analysis - Bollywood",
    "Guru (Jupiter) Yagya",
    "Hair Fall Treatment in Medical Astrology",
    "Handmade Horoscope-Kundli",
    "Hearing Loss Cure in Medical Astrology",
    "Health Betterment Yagya",
    "Herpes simplex virus (HSV) Treatment in Medical Astrology",
    "How Will Be My Married Life",
    "Huntington's Chorea Treatment In Medical Astrology",
    "Impotence Treatment in Medical Astrology",
    "Infants Disease Cure in Medical Astrology",
    "Infertility solution for Couples",
    "Instant Astro Question",
    "Instant Consultation – Within 1 Day By: Prashant Kapoor Astrologer",
    "Insomnia Treatment in Medical Astrology",
    "Itching Treatment In Medical Astrology",
    "Kaalsarpa Yoga Solutions",
    "Kala Azar Cure in Medical Astrology",
    "Kanak Dhara Yagya",
    "Kidney Treatment in Medical Astrology",
    "Kundali Match of the Cast & Crew",
    "Ketu Yagya",
    "Know your spouse from your Horoscope",
    "Laal Kitab Report",
    "Legal Astrology",
    "Libido Treatment in Medical Astrology",
    "Lipoma Treatment in Medical Astrology",
    "Liver Cirrhosis Treatment in Medical Astrology",
    "Liver Treatment in Medical Astrology",
    "Love and Relationship Astrology",
    "Love Compatibility Astrology Check",
    "Low Libido Treatment In Male By Medical Astrology",
    "Maha Durga Yagya or Maha Shakti Pooja",
    "Maha Ganapati Yagya",
    "Maha Lakshmi Yagya",
    "Maha Saraswati Yagya",
    "Maha Vishnu Yagya",
    "Mahamritunjaya Tula Daan",
    "Mahamrityunjaya Yagya",
    "Manmohini Yagya",
    "Mangal Mars Yagya-Yagya for Manglik",
    "Marriage and Family Counselling",
    "Marriage Problem Eradication Yagya",
    "Marital Problems Solutions",
    "Medical Astrology Consultation",
    "Medical Astrology Treatment of Bell's Palsy",
    "Medical Astrology Treatment of Glaucoma",
    "Mental Health Counselling",
    "Migraine Treatment in Medical Astrology",
    "Money and Career Astrology",
    "Mool Shanti Pooja Vidhi or Mool Yagya",
    "Motor Neuron Cure in Medical Astrology",
    "Movie Naming Convention Bollywood Astrology",
    "Movie Naming Convention Numerology",
    "Movie Set-Location Finalization",
    "Muhurata for Marriage",
    "Mundan Sanskar",
    "My Marriage will be Love or Arranged",
    "Navagraha Yagya",
    "Navgraha Yagya",
    "Narayan Bali Yagya",
    "Neuralgia Treatment in Medical Astrology",
    "New Venture Analysis",
    "New born child Yagya",
    "Nightfall Treatment in Medical Astrology",
    "Numerology Consultation",
    "OCD Treatment in Medical Astrology",
    "Obesity Treatment in Medical Astrology",
    "Oligospermia Treatment in Medical Astrology",
    "One Year Business-Varshaphala",
    "Online Hand Reading for Bollywood",
    "Osteoporosis Cure in Medical Astrology",
    "Other Divine Yagyas-Narsimha-Krishna-Rama-Hanuman-Vishwakarma-Yagya",
    "Palm Reading",
    "Palmistry Personal Consultation for Bollywood",
    "Parkinson Treatment in Medical Astrology",
    "Partnership Analysis",
    "Past Life Dosha Reading for Couple",
    "PCOD Treatment in Medical Astrology",
    "Performance of Rites to Honor the Deceased Narayan Bali Yagya",
    "Personalized Numerology Report",
    "Piles Treatment In Medical Astrology",
    "Pituitary Gland Disorder Cure in Medical Astrology",
    "Polycystic Kidney Disease Treatment In Medical Astrology",
    "Powerful logo cards",
    "Prashna Kundli",
    "Premenstrual Syndrome cure in Medical Astrology",
    "Premature Ejaculation Treatment Through Medical Astrology",
    "Premature Menopause Treatment in Medical Astrology",
    "Premium Consultation within 25 working days",
    "Premium Consultation within 7 working days",
    "Prediction of My Marriage",
    "Problem Eradication Yagya",
    "Property Vehicle Sale and Buy Analysis",
    "Putra Kameshti Yagam",
    "Rahu Yagya",
    "Raising finance",
    "Relocation Report",
    "Remedial Astrology for Delay in Marriage",
    "Remedies for Delayed Marriage",
    "Right Employee",
    "Rudrabhishek Yagya",
    "Rudraksha Therapy Consultation",
    "Shat Chandi Path Yagya",
    "Sciatica Treatment In Medical Astrology",
    "Schizophrenia Treatment in Medical Astrology",
    "Sex Power Enhancement in Medical Astrology",
    "Shani (Saturn) Yagya",
    "Shubh Muhurat-Date Day Time",
    "Shubharambha Inauguration Yagya",
    "Shukra (Venus) Yagya",
    "Skin Disease Treatment In Medical Astrology",
    "Solemnization of My Marriage When",
    "Spouse Search Name Report",
    "Stock Market Astrology Predictions",
    "Surya (Sun) Yagya",
    "Tarot Card Consultation",
    "Ten Years Astrological Predictions",
    "Test Service Form",
    "Tinnitus Treatment in Medical Astrology",
    "Tough Times and Remedial Astrology",
    "Urticaria Treatment In Medical Astrology",
    "Vaastu Shastra Consultation",
    "Vaastu Shanti Puja Vidhi or Vastu Yagya",
    "Varicose Veins Treatment in Medical Astrology",
    "Varshaphal Report 1 year Astrology Predictions",
    "Vedic Education Report Predictions",
    "Vedic Gemstone Recommendation",
    "Vedic Matchmaking",
    "Vedic Matchmaking Package",
    "Vedic Yagya for Business Success Superior",
    "Vertigo Treatment in Medical Astrology",
    "Voice Loss Treatment in Medical Astrology",
    "Wedding Anniversary Yagya",
    "Weight Loss Treatment in Medical Astrology",
    "When Solemnization of My Marriage",
    "Whooping Cough Cure in Medical Astrology",
    "Wilson's disease treatment in Medical Astrology",
    "Yagya For Happy Life",
    "Yagya Specially For You",
    "Yagya for Career Development Promotion",
    "Yagya for Corporate Success or Solution",
    "Yagya for Domestic Problem Solutions",
    "Yagya for Fortunate Development of Children",
    "Yagya for Freedom from Bondage",
    "Yagya for Good and Peaceful Sleep",
    "Yagya for Memory Improvement",
    "Yagya for Peace of Mind",
    "Yagya for Protection from enemies or Govt.",
    "Yagya for Quick Results",
    "Yagya for Removal of Obstacle",
    "Yagya for Success in Education and Learning",
    "Yagya for finding suitable Job",
    "Yagya to Avoid Alcohol Drinks and Drug Addiction",
    "Yagya to Overcome from Fear and Anxiety",
    "Yagya to find match for marriage",
    "Yagyas and Anushthan",
    "Yagyas for Spiritual progress and Enlightenment",
    "Yagyas for safe Journey",
    "Yellow Fever Treatment In Medical Astrology",
    "2025 Astrological Career and Finance Fortune Report",
    "2025 Horoscope Report",
    "2025 Love Astrology Report | 2025 Marriage Astrology Report",
  ],

  mode: [
    "CCavenue",
    "UPI",
    "PayPal",
    "Corporate Account",
    "Pristdel",
    "Cash In Hand",
    "Cash to Saynoee",
    "Bank Account",
    "NEFT",
    "Cash Deposit",
    "Online",
    "Cheque Deposit",
  ],
  category: ["Consultation", "Products", "Gemstones"],
  overallRating: Array.from({ length: 10 }, (_, i) => i + 1),
};
