export const nonEditableFields = [
  "transactionId",
  "dateOfPayment",
  "handlerId",
];

export const hiddenFields = [
  "communication",
  "solutions",
  "solDetails",
  "overallRating",
  "remarks",
  "qualityDesc",
  "feedStatus",
  "additionalInfo",
  "feedbackComment",
  "airBillNo",
  "productsName",
  "gems3",
  "gems4",
];

export const expectedHeaders = {
  dateOfPayment: "",
  customerName: "",
  amount: "",
  pendingAmount: "",
  refund: "",
  status: "",
  service: "",
  mobile1: "",
  mobile2: "",
  email1: "",
  email2: "",
  expert: "",
  handlerId: "",
  handleBy: "",
  mode: "",
  country: "",
  state: "",
  transactionId: "",
  sheet: "",
  remark: "",
  gems: "",
  gems1: "",
  gems2: "",
  gems3: "",
  gems4: "",
  communication: "",
  solutions: "",
  solDetails: "",
  overallRating: "",
  remarks: "",
  qualityDesc: "",
  feedStatus: "",
  additionalInfo: "",
  feedbackComment: "",
  address: "",
  airBillNo: "",
  productsName: "",
  skuNo: "",
  category: "",
};

export const headerLabels = {
  dateOfPayment: "Date of Payment",
  customerName: "Customer Name",
  amount: "Amount",
  pendingAmount: "Pending Amount",
  refund: "Refund",
  status: "Status",
  service: "Service",
  mobile1: "Mobile 1",
  mobile2: "Mobile 2",
  email1: "Email 1",
  email2: "Email 2",
  expert: "Expert",
  handlerId: "Handler ID",
  handleBy: "Handle By",
  mode: "Mode",
  country: "Country",
  state: "State",
  transactionId: "Transaction ID",
  sheet: "Sheet",
  remark: "Remark",
  gems: "Gems",
  gems1: "Gems 1",
  gems2: "Gems 2",
  gems3: "Gems 3",
  gems4: "Gems 4",
  communication: "Communication",
  solutions: "Solutions",
  solDetails: "Sol Details",
  overallRating: "Overall Rating",
  remarks: "Remarks",
  qualityDesc: "Quality Desc",
  feedStatus: "Feed Status",
  additionalInfo: "Additional Info",
  feedbackComment: "Feedback Comment",
  address: "Address",
  airBillNo: "Air Bill No.",
  productsName: "Product Name",
  skuNo: "SKU NO.",
  category: "Category",
};

// =============================
// Filter configuration
// =============================
export const categoryOptionsConfig = [
  { key: "status", label: "Status" },
  { key: "mode", label: "Payment Mode" },
  { key: "service", label: "Service" },
  { key: "handleBy", label: "Handled By" },
  { key: "expert", label: "Expert" },
  { key: "country", label: "Country" },
];
